server:
  port: 80
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 300m
spring:
  mvc:
    static-path-pattern: /**
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    #oracle.jdbc.OracleDriver
    url: jdbc:mariadb://localhost:3306/hideon404
    #jdbc:oracle:thin:@localhost:1521:xe
    username: hideon
    password: 404

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    #show-sql: true
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false

hideon:
  key: 404

mybatis:
  type-aliases-package: com.cos.blog
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    jdbc-type-for-null: null
    cache-enabled: false
